### PR TITLE
Large Changeset: Allow use with MRI Rubies and/or JRuby

### PR DESCRIPTION
**Pull request by jgdavey**
Disclaimer: This changeset makes many assumptions, including that RSpec and Bundler should be used for development.

More importantly, though, this update allows the ZXing library to be used from JRuby or MRI (using the jruby-jars gem). It borrows the pattern developed in the bernerdschaefer/akephalos library, namely, that if MRI is being used, it spins up a client process to a DRb instance of the ZXing module, which is served using the vendored JRuby withing the jruby-jars gem.

This technique importantly does not assume that JRuby is installed, which makes it suitable for use with RVM, for example. It only requires that java itself be installed on the system, and what system does not have java installed these days?

Also, I removed the Decodable mixin, because the ROI of getting in working in both JRuby and MRI seemed low given the simplicity of the ZXing library itself.

### CODE REVIEW

**Comment by smparkes** [comment]
Don't know what Ecin thinks of this ...

I actually have a branch that integrates the C++ version of zxing for use with MRI and MacRuby while using the Java code for JRuby. Haven't gotten around to releasing it though ...

I don't which approach is preferred. Maybe I should make my stuff into a different gem. The C++ code for qr codes is pretty close to the Java code but the 1D code support is not as complete.

**Comment by ecin** [comment]
Nice job on getting this running under MRI!

I would like to add back in the ability to handle files, paths and urls (as well as anything that responds to #path) to maintain the same API we have now.

**Comment by jgdavey** [comment]
I'm definitely on board with that. I can port over most of the old test suite for those particulars and re-implement. I'll update the pull request at that point, (or close this one and re-open another).

Thanks!

**Comment by jgdavey** [comment]
I've updated the code to restore the original API, and updated the documentation accordingly.

**Comment by ecin** [comment]
Looks great. I'll merge soon.

**Comment by ecin** [comment]
Merged! zxing 0.2 is now out in the wild. Thanks again!

**Comment by jgdavey** [comment]
Awesome and congrats!

**Pull request merged**
