### PR TITLE
Allow the passing of Hints to #decode.  

### PR DESCRIPTION
**Pull request by rondale-sc**
Hints are passed to decode as a hashtable.  

[Barcode Formats from google code](http://www.google.com/codesearch#Wxg6JYYzJv0/trunk/TalkingZxing/core/src/com/google/zxing/BarcodeFormat.java&q=BarcodeFormat&type=cs)

> Encapsulates a type of hint that a caller may pass to a barcode reader to help it
>    more quickly or accurately decode it. It is up to implementations to decide what,
>    if anything, to do with the information that is supplied.

### CODE REVIEW

**Comment by ecin** [comment]
Awesome. Could you write some tests to describe the new behavior?

**Comment by rondale-sc** [comment]
Absolutely, I'll see if I can get to it today.

**Comment by rondale-sc** [comment]
In non-try-harder mode the 1d readers are fired first, when try-harder is specified they are fired last.  So you get the change in behavior.

**Comment by palfvin** [comment]
I'd like to use this mechanism. Is there something holding up the merge?

**Comment by ecin** [comment]
Don't think anything is holding this back, @palfvin. Let me dust off some cobwebs.

**Comment by palfvin** [comment]
Thanks, @ecin.  On a slightly related point, I don't know if you (or other clients) have run into the "phantom finder detection on perfectly aligned/clean QR codes" problem, but the way the discussion is going at https://code.google.com/p/zxing/issues/detail?id=1745#makechanges, a workaround _may_ require passing ZXing failure information back to the Ruby client. Just thought I'd mention it while you were refreshing your memory on the code.

**Comment by palfvin** [comment]
How are things going? On a related point, I really need the latest jars from zxing. I was going to try and figure out how to "roll my own", but thought I'd check in first.

**Pull request closed without merging**
